# Generated by Django 5.0.1 on 2024-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='species',
            field=models.CharField(default='Zebra Finch', max_length=100),
        ),
    ]
